version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq-cluster:3.8.1
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_NODENAME=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=mmpsoft.com
    volumes:
      - /volumes/rabbitmq/rabbitmq1:/var/lib/rabbitmq
    ports:
      - "15673:15672"
    networks:
      rabbitmq-cluster:
        aliases:
          - rabbitmq1

  rabbitmq2:
    image: rabbitmq-cluster:3.8.1
    hostname: rabbitmq2
    container_name: rabbitmq2
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_NODENAME=rabbitmq2
      - RABBITMQ_ERLANG_COOKIE=mmpsoft.com
    volumes:
      - /volumes/rabbitmq/rabbitmq2:/var/lib/rabbitmq
    depends_on:
      - rabbitmq1
    networks:
      rabbitmq-cluster:
        aliases:
          - rabbitmq2

  rabbitmq3:
    image: rabbitmq-cluster:3.8.1
    hostname: rabbitmq3
    container_name: rabbitmq3
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_NODENAME=rabbitmq3
      - RABBITMQ_ERLANG_COOKIE=mmpsoft.com
    volumes:
      - /volumes/rabbitmq/rabbitmq3:/var/lib/rabbitmq
    depends_on:
      - rabbitmq1
    networks:
      rabbitmq-cluster:
        aliases:
          - rabbitmq3

  rabbitmq-haproxy:
    image: haproxy:latest
    hostname: rabbitmq-haproxy
    container_name: rabbitmq-haproxy
    networks:
      rabbitmq-cluster:
        aliases:
          - rabbitmq-haproxy
    volumes:
      - /volumes/rabbitmq-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1080:1080"

networks:
  rabbitmq-cluster:
    name: rabbitmq-cluster
    driver: bridge